In [1]:
%config IPcompleter.use_jedi=False

In [2]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data=pd.read_csv('heart_disease_dataset.csv',sep=';')
data.head(50)

age  sex  chest_pain_type  resting_blood_pressure  cholesterol  \
0    63    1                3                     145          233   
1    37    1                2                     130          250   
2    41    0                1                     130          204   
3    56    1                1                     120          236   
4    57    0                0                     120          354   
5    57    1                0                     140          192   
6    56    0                1                     140          294   
7    44    1                1                     120          263   
8    52    1                2                     172          199   
9    57    1                2                     150          168   
10   54    1                0                     140          239   
11   48    0                2                     130          275   
12   49    1                1                     130          266   
13   64    1                3                     110          211   
14   58    0                3                     150          283   
15   50    0                2                     120          219   
16   58    0                2                     120          340   
17   66    0                3                     150          226   
18   43    1                0                     150          247   
19   69    0                3                     140          239   
20   59    1                0                     135          234   
21   44    1                2                     130          233   
22   42    1                0                     140          226   
23   61    1                2                     150          243   
24   40    1                3                     140          199   
25   71    0                1                     160          302   
26   59    1                2                     150          212   
27   51    1                2                     110          175   
28   65    0                2                     140          417   
29   53    1                2                     130          197   
30   41    0                1                     105          198   
31   65    1                0                     120          177   
32   44    1                1                     130          219   
33   54    1                2                     125          273   
34   51    1                3                     125          213   
35   46    0                2                     142          177   
36   54    0                2                     135          304   
37   54    1                2                     150          232   
38   65    0                2                     155          269   
39   65    0                2                     160          360   
40   51    0                2                     140          308   
41   48    1                1                     130          245   
42   45    1                0                     104          208   
43   53    0                0                     130          264   
44   39    1                2                     140          321   
45   52    1                1                     120          325   
46   44    1                2                     140          235   
47   47    1                2                     138          257   
48   53    0                2                     128          216   
49   53    0                0                     138          234   

    fasting_blood_sugar  rest_ecg  max_heart_rate_achieved  \
0                     1         0                      150   
1                     0         1                      187   
2                     0         0                      172   
3                     0         1                      178   
4                     0         1                      163   
5                     0         1                      148   

In [4]:
data.shape

(303, 14)

In [5]:
data.dtypes

age                          int64
sex                          int64
chest_pain_type              int64
resting_blood_pressure       int64
cholesterol                  int64
fasting_blood_sugar          int64
rest_ecg                     int64
max_heart_rate_achieved      int64
exercise_induced_angina      int64
st_depression              float64
st_slope                     int64
num_major_vessels            int64
thalassemia                  int64
target                       int64
dtype: object

In [6]:
data.isnull().sum()

age                        0
sex                        0
chest_pain_type            0
resting_blood_pressure     0
cholesterol                0
fasting_blood_sugar        0
rest_ecg                   0
max_heart_rate_achieved    0
exercise_induced_angina    0
st_depression              0
st_slope                   0
num_major_vessels          0
thalassemia                0
target                     0
dtype: int64

In [7]:
data.describe()

age         sex  chest_pain_type  resting_blood_pressure  \
count  303.000000  303.000000       303.000000              303.000000   
mean    54.366337    0.683168         0.966997              131.623762   
std      9.082101    0.466011         1.032052               17.538143   
min     29.000000    0.000000         0.000000               94.000000   
25%     47.500000    0.000000         0.000000              120.000000   
50%     55.000000    1.000000         1.000000              130.000000   
75%     61.000000    1.000000         2.000000              140.000000   
max     77.000000    1.000000         3.000000              200.000000   

       cholesterol  fasting_blood_sugar    rest_ecg  max_heart_rate_achieved  \
count   303.000000           303.000000  303.000000               303.000000   
mean    246.264026             0.148515    0.528053               149.646865   
std      51.830751             0.356198    0.525860                22.905161   
min     126.000000             0.000000    0.000000                71.000000   
25%     211.000000             0.000000    0.000000               133.500000   
50%     240.000000             0.000000    1.000000               153.000000   
75%     274.500000             0.000000    1.000000               166.000000   
max     564.000000             1.000000    2.000000               202.000000   

       exercise_induced_angina  st_depression    st_slope  num_major_vessels  \
count               303.000000     303.000000  303.000000         303.000000   
mean                  0.326733       1.039604    1.399340           0.729373   
std                   0.469794       1.161075    0.616226           1.022606   
min                   0.000000       0.000000    0.000000           0.000000   
25%                   0.000000       0.000000    1.000000           0.000000   
50%                   0.000000       0.800000    1.000000           0.000000   
75%                   1.000000       1.600000    2.000000           1.000000   
max                   1.000000       6.200000    2.000000           4.000000   

       thalassemia      target  
count   303.000000  303.000000  
mean      2.313531    0.544554  
std       0.612277    0.498835  
min       0.000000    0.000000  
25%       2.000000    0.000000  
50%       2.000000    1.000000  
75%       3.000000    1.000000  
max       3.000000    1.000000

In [8]:
x=np.array(data.drop(['target'],1))
y=np.array(data['target']).reshape(-1,1)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [10]:
y

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [32]:
x.shape

(303, 13)

In [11]:
def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

def mse_loss(y_true, y_pred):
  # y_true and y_pred are numpy arrays of the same length.
  return ((y_true - y_pred) ** 2).mean()

def mse_loss_derivative(y_true, y_pred):
  # y_true and y_pred are numpy arrays of the same length.
  return (2*(y_true - y_pred))

class ArtificialNeuralNetwork:
    def __init__(self, x, y):
        self.IN      = x
        self.W1   = np.random.rand(self.IN.shape[1],6) 
        self.W2   = np.random.rand(6,4) 
        self.W3   = np.random.rand(4,1)                 
        self.y          = y
        self.OUT     = np.zeros(self.y.shape)
        self.learning_rate = 0.1

    def feed_forward(self):
        self.HIDDEN_LAYER_1 = sigmoid(np.dot(self.IN, self.W1))
        self.HIDDEN_LAYER_2 = sigmoid(np.dot(self.HIDDEN_LAYER_1, self.W2))
        self.output = sigmoid(np.dot(self.HIDDEN_LAYER_2, self.W3))

    def back_propagate(self):
        # application of the chain rule to find derivative of the loss function with respect to W2 and W1
        d_W3 = np.dot(self.HIDDEN_LAYER_2.T, (mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output)))
        
        d_W2 = np.dot(self.HIDDEN_LAYER_1.T, (np.dot(mse_loss_derivative(self.y, self.output) * 
                                                    sigmoid_derivative(self.output),self.W3.T)*
                      sigmoid_derivative(self.HIDDEN_LAYER_2)))
        d_W1 = np.dot(self.IN.T, (np.dot(np.dot(mse_loss_derivative(self.y, self.output) * 
                                          sigmoid_derivative(self.output),self.W3.T)*sigmoid_derivative(self.HIDDEN_LAYER_2), self.W2.T)
                      *sigmoid_derivative(self.HIDDEN_LAYER_1)))
        print("dw3",d_W3)
        # update the weights with the derivative (slope) of the loss function
        self.W1 += self.learning_rate*d_W1
        self.W2 += self.learning_rate*d_W2
        self.W3 += self.learning_rate*d_W3
                                   
    def train(self, epochs,learning_rate):
        self.learning_rate=learning_rate
        for i in range(epochs):
            self.feed_forward()
            self.back_propagate()
        print("Successfully Trained the Model")
        print("Weights 1:", self.W1)
        print("Weights 2:", self.W2)
        print("Weights 3:", self.W3)
    
    def print_output(self):
        print(self.output)



In [13]:

epochs = 10
learning_rate = 0.1
ann = ArtificialNeuralNetwork(x,y)
ann.train(epochs, learning_rate)

dw3 [[-15.69677525]
 [-15.4974189 ]
 [-15.26641067]
 [-15.49071897]]
dw3 [[11.96718526]
 [11.97858012]
 [12.0047309 ]
 [11.98338112]]
dw3 [[-17.73025689]
 [-17.35517804]
 [-16.89993231]
 [-17.44022124]]
dw3 [[3.65352758]
 [3.66175891]
 [3.66836426]
 [3.69176244]]
dw3 [[8.89915242]
 [8.90293841]
 [8.9074207 ]
 [8.96266147]]
dw3 [[16.48359907]
 [16.50772818]
 [16.7145705 ]
 [16.30767075]]
dw3 [[-2.67162782]
 [-2.59314257]
 [-2.53181392]
 [-2.54257671]]
dw3 [[-5.40431948]
 [-5.2165589 ]
 [-5.06880827]
 [-5.12392739]]
dw3 [[-15.31011234]
 [-14.52465266]
 [-13.88873619]
 [-14.51130433]]
dw3 [[16.80415652]
 [16.15808808]
 [16.09532671]
 [17.54639279]]
Successfully Trained the Model
Weights 1: [[0.23484079 0.73833778 0.75995119 0.7352966  0.98814915 0.62142972]
 [0.16760533 0.17164746 0.16035252 0.19773736 0.07829207 0.5138139 ]
 [0.82665676 0.10377463 0.41781358 0.59318148 0.68587125 0.11623569]
 [0.8419974  0.15380492 0.3713681  0.79504824 0.96373664 0.79167309]
 [0.99957891 0.69927297 0.48

In [14]:
ann.print_output()

[[0.14576814]
 [0.16288367]
 [0.17016336]
 [0.15380281]
 [0.14542595]
 [0.16945418]
 [0.16452239]
 [0.15796223]
 [0.13576227]
 [0.14138332]
 [0.15342562]
 [0.15813107]
 [0.15333231]
 [0.1557045 ]
 [0.1369752 ]
 [0.16565878]
 [0.14497797]
 [0.14808903]
 [0.15320218]
 [0.13535563]
 [0.15754892]
 [0.14484008]
 [0.16372705]
 [0.1364873 ]
 [0.1391109 ]
 [0.13522321]
 [0.13662157]
 [0.16874565]
 [0.13564896]
 [0.16576192]
 [0.1700598 ]
 [0.16078284]
 [0.16782227]
 [0.16719001]
 [0.1483686 ]
 [0.16903294]
 [0.13839657]
 [0.14230825]
 [0.13781182]
 [0.13663686]
 [0.14776425]
 [0.16980831]
 [0.17329751]
 [0.17184305]
 [0.15594775]
 [0.15121955]
 [0.16063159]
 [0.16205349]
 [0.17244404]
 [0.16896317]
 [0.16487544]
 [0.16812523]
 [0.13734664]
 [0.17163645]
 [0.15196574]
 [0.15048339]
 [0.17054179]
 [0.17127637]
 [0.17046139]
 [0.16252726]
 [0.14512493]
 [0.15430983]
 [0.17004814]
 [0.172055  ]
 [0.14274057]
 [0.16878683]
 [0.16531354]
 [0.17146809]
 [0.16641246]
 [0.1633559 ]
 [0.165405  ]
 [0.14